# Configuraci贸n de seguridad para Dependabot
# Este archivo define configuraciones adicionales de seguridad

# Habilitar alertas de seguridad de Dependabot
security-advisories:
  - enabled: true

# Configuraci贸n de vulnerabilidades
vulnerability-alerts:
  - enabled: true
  - auto-dismiss-low-severity: false

# Configuraci贸n de actualizaciones de seguridad
security-updates:
  - enabled: true
  - auto-merge-patch: true
  - auto-merge-minor: false

# Ecosistemas monitoreados
ecosystems:
  - pip
  - github-actions

# Configuraci贸n de notificaciones
notifications:
  - email: true
  - web: true
