blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ironwolphern/lab-genai/discussions
    about: Para preguntas generales, ideas o discusiones sobre el proyecto
  - name: 🔒 Reporte de Seguridad
    url: https://github.com/ironwolphern/lab-genai/security/advisories/new
    about: Para reportar vulnerabilidades de seguridad de forma privada
  - name: 📖 Documentación
    url: https://github.com/ironwolphern/lab-genai#readme
    about: Consulta la documentación del proyecto antes de crear un issue
