name: Dependabot Auto-Merge

# Este workflow se ejecuta cuando Dependabot abre un PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    # Solo ejecutar si el PR viene de Dependabot
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar linting
        run: |
          # Ejecutar herramientas de linting si están disponibles
          if command -v black &> /dev/null; then
            black --check --diff .
          fi
          if command -v flake8 &> /dev/null; then
            flake8 .
          fi
          if command -v pylint &> /dev/null; then
            pylint *.py --disable=all --enable=E
          fi

      - name: Ejecutar tests
        run: |
          # Ejecutar tests si están disponibles
          if command -v pytest &> /dev/null; then
            pytest --no-header -v
          else
            # Ejecutar una prueba básica del archivo principal
            python -m py_compile main.py
            python main.py || true
          fi

      - name: Obtener información del PR de Dependabot
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-aprobar PR menores de Dependabot
        # Solo auto-aprobar actualizaciones patch y minor
        if: steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge PR menores de Dependabot
        # Solo auto-merge actualizaciones patch de dependencias de desarrollo
        if: |
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' &&
          contains(steps.dependabot-metadata.outputs.dependency-names, 'black') ||
          contains(steps.dependabot-metadata.outputs.dependency-names, 'flake8') ||
          contains(steps.dependabot-metadata.outputs.dependency-names, 'pylint') ||
          contains(steps.dependabot-metadata.outputs.dependency-names, 'pytest')
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
